version: '2'

tester:
  port: 8090
  operationMode: blockchain #exchange or blockchain

booster:
  #addr: 15.164.85.106
  #addr: 172.16.20.188
  addr: localhost

exchange:
  #addr: 13.209.106.250
  addr: localhost

members:
  count: 5
  prefix: aa


